### PR TITLE
Add new Identifier element to BaseNodeType

### PR DESCRIPTION
**Pull request by CTrabant**
Add new IdentifierType and Identifier element to BaseNodeType for use at Network, Station and Channel level elements

### CODE REVIEW

**Comment by megies** [comment]
According to today's mail on [fdsn-wg2-data] this should be merged, I guess?

**Comment by crotwell** [comment]
Version bump?

**Comment by CTrabant** [comment]
No version bump, this is not a new release of StationXML schema.  WG2 has not approved anything beyond adding the DOI element.  Personally I would like to see more of the approved changes be considered before we cut a new release.

**Comment by crotwell** [comment]
OK, but in that case might be safest to mark version as 1.1-beta or
something? Otherwise you have schema files out on internet, looking like
they come from authoritative source with additions and old version. Just
seems safe to mark it as non-1.0 somehow.

Philip

**Comment by megies** [comment]
> OK, but in that case might be safest to mark version as 1.1-beta or something?

I agree, while it's additional work to temporarily set a `dev` or `beta` version number it would probably be safer to not have "1.0" in the version field in between releases..

**Comment by chad-iris** [comment]
> >OK, but in that case might be safest to mark version as 1.1-beta or something?

>I agree, while it's additional work to temporarily set a dev or beta version number it would probably be safer to not have "1.0" in the version field in between releases..

Agreed.  I have set the master branch version to simply "dev" in commit 61fa828129eb50cb2a29599bd829116e84fa5ec2.

This should avoid any confusion with approved releases.

**Comment by petrrr** [comment]
Hi, shouldn't we release this at some point?

This is around for quite some time. It was formally approve, but we still cannot implement anything, as long as it cannot be validated. I guess other changes might still take some extra time before they are approved and ready for release.

**Pull request merged**
